spring:
  profiles: local
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost/devoxx?useUnicode=yes&characterEncoding=UTF-8
    username: devoxx
    password: devoxx
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

